language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t yuryshkoda/udemy-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true yuryshkoda/udemy-docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "udemy-docker-react"
    env: "UdemyDockerReact-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-432610128422"
    bucket_path: "udemy-docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY